package usecase

import (
	"context"
	"errors"
	"fmt"
	"time"

	"finance-webapps/backend/internal/domain"
	"github.com/google/uuid"
)

type paymentScheduleUsecase struct {
	psRepo   domain.PaymentScheduleRepository
	phRepo   domain.PaymentHistoryRepository
	auditLog domain.AuditLogRepository
}

func NewPaymentScheduleUsecase(
	psRepo domain.PaymentScheduleRepository,
	phRepo domain.PaymentHistoryRepository,
	auditLog domain.AuditLogRepository,
) domain.PaymentScheduleUsecase {
	return &paymentScheduleUsecase{
		psRepo:   psRepo,
		phRepo:   phRepo,
		auditLog: auditLog,
	}
}

func (u *paymentScheduleUsecase) GetAll(ctx context.Context, filter domain.PaymentScheduleFilter) ([]domain.PaymentSchedule, int64, error) {
	return u.psRepo.GetAll(ctx, filter)
}

func (u *paymentScheduleUsecase) GetByID(ctx context.Context, id uuid.UUID) (*domain.PaymentSchedule, error) {
	return u.psRepo.GetByID(ctx, id)
}

func (u *paymentScheduleUsecase) GenerateSchedulesForService(ctx context.Context, service *domain.Service) error {
	now := time.Now()
	var schedules []domain.PaymentSchedule

	for i := 0; i < 3; i++ {
		targetMonth := now.AddDate(0, i, 0)
		periodStr := targetMonth.Format("2006-01")

		year := targetMonth.Year()
		month := targetMonth.Month()
		lastDay := time.Date(year, month+1, 0, 0, 0, 0, 0, time.UTC).Day()
		dueDay := service.DueDay
		if dueDay > lastDay {
			dueDay = lastDay
		}

		dueDate := time.Date(year, month, dueDay, 0, 0, 0, 0, time.Local)
		today := time.Date(now.Year(), now.Month(), now.Day(), 0, 0, 0, 0, now.Location())

		status := "UPCOMING"
		if dueDate.Before(today) {
			status = "OVERDUE"
		} else if dueDate.Equal(today) {
			status = "DUE"
		}

		schedule := domain.PaymentSchedule{
			ID:              uuid.New(),
			ServiceID:       service.ID,
			Period:          periodStr,
			DueDate:         dueDate,
			Amount:          service.Amount,
			RemainingAmount: service.Amount,
			Status:          status,
			Notes:           "Generated by schedule engine",
		}
		schedules = append(schedules, schedule)
	}

	return u.psRepo.BatchCreate(ctx, schedules)
}

func (u *paymentScheduleUsecase) MarkAsPaid(ctx context.Context, req domain.MarkAsPaidRequest, userID int64) (*domain.PaymentSchedule, error) {
	paymentDate, err := time.Parse("2006-01-02", req.PaymentDate)
	if err != nil {
		return nil, errors.New("invalid payment date format (expected YYYY-MM-DD)")
	}

	if paymentDate.After(time.Now()) {
		return nil, errors.New("payment date cannot be in the future")
	}

	schedule, err := u.psRepo.GetByID(ctx, req.ScheduleID)
	if err != nil {
		return nil, errors.New("payment schedule not found")
	}

	if schedule.Status == "PAID" {
		return nil, errors.New("payment schedule is already fully paid")
	}

	if req.PaymentAmount <= 0 {
		return nil, errors.New("payment amount must be greater than zero")
	}

	newRemaining := schedule.RemainingAmount - req.PaymentAmount
	var newStatus string
	if newRemaining <= 0 {
		newStatus = "PAID"
		newRemaining = 0
	} else {
		newStatus = "PARTIALLY_PAID"
	}

	schedule.RemainingAmount = newRemaining
	schedule.Status = newStatus
	schedule.PaymentDate = &paymentDate
	if req.Notes != "" {
		schedule.Notes = req.Notes
	}

	if err := u.psRepo.Update(ctx, schedule); err != nil {
		return nil, err
	}

	// Grace Period Transition: If fully paid, ensure next period schedule exists for next cycle!
	if newStatus == "PAID" {
		nextDate := schedule.DueDate.AddDate(0, 1, 0)
		nextPeriod := nextDate.Format("2006-01")
		_, errExists := u.psRepo.GetByServiceAndPeriod(ctx, schedule.ServiceID, nextPeriod)
		if errExists != nil {
			nextSchedule := domain.PaymentSchedule{
				ID:              uuid.New(),
				ServiceID:       schedule.ServiceID,
				Period:          nextPeriod,
				DueDate:         nextDate,
				Amount:          schedule.Amount,
				RemainingAmount: schedule.Amount,
				Status:          "UPCOMING",
				Notes:           "Grace Period - Auto-generated for next billing cycle",
			}
			_ = u.psRepo.Create(ctx, &nextSchedule)
		}
	}

	// Record Payment History
	history := &domain.PaymentHistory{
		ID:               uuid.New(),
		ScheduleID:       schedule.ID,
		PaymentDate:      paymentDate,
		PaymentAmount:    req.PaymentAmount,
		PaymentReference: req.PaymentReference,
		PaymentMethod:    req.PaymentMethod,
		PaymentProof:     req.PaymentProof,
		Notes:            req.Notes,
		PaidBy:           userID,
	}

	if err := u.phRepo.Create(ctx, history); err != nil {
		return nil, err
	}

	// Audit Log
	_ = u.auditLog.Create(ctx, &domain.AuditLog{
		ID:        uuid.New(),
		UserID:    &userID,
		Action:    "PAYMENT",
		Entity:    "PaymentSchedule",
		EntityID:  schedule.ID.String(),
		Timestamp: time.Now(),
	})

	return schedule, nil
}

func (u *paymentScheduleUsecase) BulkMarkAsPaid(ctx context.Context, req domain.BulkMarkAsPaidRequest, userID int64) ([]uuid.UUID, []string, error) {
	var successIDs []uuid.UUID
	var errMessages []string

	for _, id := range req.ScheduleIDs {
		schedule, err := u.psRepo.GetByID(ctx, id)
		if err != nil {
			errMessages = append(errMessages, fmt.Sprintf("Schedule %s not found", id))
			continue
		}

		singleReq := domain.MarkAsPaidRequest{
			ScheduleID:       id,
			PaymentDate:      req.PaymentDate,
			PaymentAmount:    schedule.RemainingAmount, // Bulk mark as paid full remaining amount
			PaymentReference: req.PaymentReference,
			PaymentMethod:    req.PaymentMethod,
			PaymentProof:     req.PaymentProof,
			Notes:            req.Notes,
		}

		_, err = u.MarkAsPaid(ctx, singleReq, userID)
		if err != nil {
			errMessages = append(errMessages, fmt.Sprintf("Schedule %s failed: %v", id, err))
		} else {
			successIDs = append(successIDs, id)
		}
	}

	return successIDs, errMessages, nil
}
